spring:
  application:
    name: Expense-AI

  datasource:
    url: jdbc:postgresql://localhost:5432/expenseai
    driverClassName: org.postgresql.Driver
    username: expenseai
    password: expenseai

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5:7b-instruct
        options:
          num-predict: 1024
          temperature: 0.2
      embedding:
        model: nomic-embed-text:latest
