receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317 # Push
    tls:
      insecure: true
  logging:
    verbosity: detailed
  prometheus:
    endpoint: 0.0.0.0:9464 # Let pull
  loki:
    endpoint: http://loki:3100/loki/api/v1/push # Push

  otlphttp/newrelic:
    endpoint: "https://otlp.eu01.nr-data.net"
    headers:
      api-key: ${NEW_RELIC_API_KEY}
#  azuremonitor:
#    connection_string: ${APPLICATIONINSIGHTS_CONNECTION_STRING}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, logging, otlphttp/newrelic]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging, otlphttp/newrelic]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, loki, otlphttp/newrelic]
